"use client";

import ProductCard from "@/components/ProductCard";

// Real automotive parts data
const automotiveProducts = [
  {
    id: "auto-bp-se-5016",
    name: "Brake Pad Segal SP-BP-SE-5016",
    price: 39,
    category: "Automotive",
    description: "(Rear) Haima S5 & Murano QASHGHAEI REANAULT KOLEOS",
    image: "/images/car-parts/WhatsApp Image 2025-12-09 at 4.41.52 PM.jpeg",
  },
  {
    id: "auto-bp-se-5022",
    name: "Brake Pad Segal SP-BP-SE-5022",
    price: 39,
    category: "Automotive",
    description: "(Front) MVM 315 & 550, Lifan x60",
    image: "/images/car-parts/WhatsApp Image 2025-12-09 at 4.41.52 PM (1).jpeg",
  },
  {
    id: "auto-bp-se-5031",
    name: "Brake Pad Segal SP-BP-SE-5031",
    price: 34,
    category: "Automotive",
    description: "(Rear) Matiz, MVM 110",
    image: "/images/car-parts/WhatsApp Image 2025-12-09 at 4.41.51 PM.jpeg",
  },
  {
    id: "auto-bp-se-5312",
    name: "Brake Pad Segal SP-BP-SE-5312",
    price: 48,
    category: "Automotive",
    description: "(Front) Toyota Yaris",
    image: "/images/car-parts/WhatsApp Image 2025-12-09 at 4.42.00 PM.jpeg",
  },
  {
    id: "auto-bp-se-6552",
    name: "Brake Pad Segal SP-BP-SE-6552",
    price: 48,
    category: "Automotive",
    description: "(Rear) MG5, MG6",
    image: "/images/car-parts/WhatsApp Image 2025-12-09 at 4.42.00 PM (1).jpeg",
  },
  {
    id: "auto-bp-se-5069",
    name: "Brake Pad Segal SP-BP-SE-5069",
    price: 49,
    category: "Automotive",
    description: "(Rear) MG5, MG6",
    image: "/images/car-parts/WhatsApp Image 2025-12-09 at 4.41.59 PM.jpeg",
  },
  {
    id: "auto-bp-se-5162",
    name: "Brake Pad Segal SP-BP-SE-5162",
    price: 34,
    category: "Automotive",
    description: "(Rear) MVM 530 & Lifan x60",
    image: "/images/car-parts/WhatsApp Image 2025-12-09 at 4.41.59 PM (1).jpeg",
  },
  {
    id: "auto-bp-se-5176",
    name: "Brake Pad Segal SP-BP-SE-5176",
    price: 34,
    category: "Automotive",
    description: "(Rear) MVM X33 & TOYOTA RAV4",
    image: "/images/car-parts/WhatsApp Image 2025-12-09 at 4.41.58 PM.jpeg",
  },
  {
    id: "auto-bp-se-5325",
    name: "Brake Pad Segal SP-BP-SE-5325",
    price: 49,
    category: "Automotive",
    description: "(Front) Haima S7",
    image: "/images/car-parts/WhatsApp Image 2025-12-09 at 4.41.58 PM (1).jpeg",
  },
  {
    id: "auto-bp-se-5334",
    name: "Brake Pad Segal SP-BP-SE-5334",
    price: 34,
    category: "Automotive",
    description: "(Rear) Lifan 820",
    image: "/images/car-parts/WhatsApp Image 2025-12-09 at 4.41.57 PM.jpeg",
  },
  {
    id: "auto-bp-se-6525",
    name: "Brake Pad Segal SP-BP-SE-6525",
    price: 34,
    category: "Automotive",
    description: "(Rear) Tiggo 8 pro",
    image: "/images/car-parts/WhatsApp Image 2025-12-09 at 4.41.57 PM (1).jpeg",
  },
  {
    id: "auto-bp-se-8500",
    name: "Brake Pad Segal SP-BP-SE-8500",
    price: 29,
    category: "Automotive",
    description: "(Rear) Pars & Samand LX & Renault Megane & Duster",
    image: "/images/car-parts/WhatsApp Image 2025-12-09 at 4.41.56 PM.jpeg",
  },
  {
    id: "auto-bp-se-8801",
    name: "Brake Pad Segal SP-BP-SE-8801",
    price: 38,
    category: "Automotive",
    description: "(Front) Renault Sandro & Lifan 520 & L90",
    image: "/images/car-parts/WhatsApp Image 2025-12-09 at 4.41.56 PM (2).jpeg",
  },
  {
    id: "auto-bp-se-8805",
    name: "Brake Pad Segal SP-BP-SE-8805",
    price: 44,
    category: "Automotive",
    description: "(Front) ARRIZO 5",
    image: "/images/car-parts/WhatsApp Image 2025-12-09 at 4.41.56 PM (1).jpeg",
  },
  {
    id: "auto-bp-se-8818",
    name: "Brake Pad Segal SP-BP-SE-8818",
    price: 32,
    category: "Automotive",
    description: "(Rear) MG5",
    image: "/images/car-parts/WhatsApp Image 2025-12-09 at 4.41.55 PM.jpeg",
  },
  {
    id: "auto-bp-se-8863",
    name: "Brake Pad Segal SP-BP-SE-8863",
    price: 34,
    category: "Automotive",
    description: "(Rear) Sonata, Kia Rio, Granvor Elantra Veloster Kia Sportage",
    image: "/images/car-parts/WhatsApp Image 2025-12-09 at 4.41.55 PM (1).jpeg",
  },
  {
    id: "auto-bp-se-8861",
    name: "Brake Pad Segal SP-BP-SE-8861",
    price: 34,
    category: "Automotive",
    description: "(Rear) Tucson & Sportage & Sonata",
    image: "/images/car-parts/WhatsApp Image 2025-12-09 at 4.41.54 PM.jpeg",
  },
  {
    id: "auto-bp-se-8860",
    name: "Brake Pad Segal SP-BP-SE-8860/8865",
    price: 49,
    category: "Automotive",
    description: "(Front) Tucson & Sportage & Sonata",
    image: "/images/car-parts/WhatsApp Image 2025-12-09 at 4.41.54 PM (1).jpeg",
  },
  {
    id: "auto-bp-se-8932",
    name: "Brake Pad Segal SP-BP-SE-8932",
    price: 34,
    category: "Automotive",
    description: "(Rear) Faw (Bestern B50)",
    image: "/images/car-parts/WhatsApp Image 2025-12-09 at 4.41.53 PM.jpeg",
  },
  {
    id: "auto-bp-se-8949",
    name: "Brake Pad Segal SP-BP-SE-8949",
    price: 49,
    category: "Automotive",
    description: "(Front) Changan CS35",
    image: "/images/car-parts/WhatsApp Image 2025-12-09 at 4.41.53 PM (1).jpeg",
  },
  {
    id: "auto-bp-se-8954",
    name: "Brake Pad Segal SP-BP-SE-8954",
    price: 37,
    category: "Automotive",
    description: "(Front) JAC S3, Hyundai Accord",
    image: "/images/car-parts/WhatsApp Image 2025-12-09 at 4.41.52 PM.jpeg",
  },
  {
    id: "auto-bp-se-5491",
    name: "Brake Pad Segal SP-BP-SE-5491",
    price: 45,
    category: "Automotive",
    description: "(Rear) Haima S7",
    image: "/images/car-parts/WhatsApp Image 2025-12-09 at 4.41.52 PM (1).jpeg",
  },
  {
    id: "auto-bp-se-6475",
    name: "Brake Pad Segal SP-BP-SE-6475",
    price: 41,
    category: "Automotive",
    description: "(Rear) Changan CS35+",
    image: "/images/car-parts/WhatsApp Image 2025-12-09 at 4.41.51 PM.jpeg",
  },
  {
    id: "auto-bp-se-8180",
    name: "Brake Pad Segal SP-BP-SE-8180",
    price: 39,
    category: "Automotive",
    description: "(Front) Toyota HiLux",
    image: "/images/car-parts/WhatsApp Image 2025-12-09 at 4.42.00 PM.jpeg",
  },
  {
    id: "auto-bp-se-6569",
    name: "Brake Pad Segal SP-BP-SE-6569",
    price: 35,
    category: "Automotive",
    description: "(Rear) Tiggo 8+",
    image: "/images/car-parts/WhatsApp Image 2025-12-09 at 4.42.00 PM (1).jpeg",
  },
  {
    id: "auto-bp-se-6587",
    name: "Brake Pad Segal SP-BP-SE-6587",
    price: 46,
    category: "Automotive",
    description: "(Front) Changan CS35",
    image: "/images/car-parts/WhatsApp Image 2025-12-09 at 4.41.59 PM.jpeg",
  },
  {
    id: "auto-bp-se-6986",
    name: "Brake Pad Segal SP-BP-SE-6986",
    price: 32,
    category: "Automotive",
    description: "(Rear) Changan Eado Sedan",
    image: "/images/car-parts/WhatsApp Image 2025-12-09 at 4.41.59 PM (1).jpeg",
  },
  {
    id: "auto-bp-se-6551",
    name: "Brake Pad Segal SP-BP-SE-6551",
    price: 49,
    category: "Automotive",
    description: "(Front) MG5, MG6",
    image: "/images/car-parts/WhatsApp Image 2025-12-09 at 4.41.58 PM.jpeg",
  },
  {
    id: "auto-bp-se-6883",
    name: "Brake Pad Segal SP-BP-SE-6883",
    price: 44,
    category: "Automotive",
    description: "(Front) ARRIZO 5",
    image: "/images/car-parts/WhatsApp Image 2025-12-09 at 4.41.58 PM (1).jpeg",
  },
  {
    id: "auto-bp-se-5068",
    name: "Brake Pad Segal SP-BP-SE-5068",
    price: 48,
    category: "Automotive",
    description: "(Rear) MG5, MG6",
    image: "/images/car-parts/WhatsApp Image 2025-12-09 at 4.41.57 PM.jpeg",
  },
  {
    id: "auto-bp-se-5046",
    name: "Brake Pad Segal SP-BP-SE-5046",
    price: 48,
    category: "Automotive",
    description: "(Front) Toyota Yaris",
    image: "/images/car-parts/WhatsApp Image 2025-12-09 at 4.41.57 PM (1).jpeg",
  },
  {
    id: "auto-bp-se-5163",
    name: "Brake Pad Segal SP-BP-SE-5163",
    price: 34,
    category: "Automotive",
    description: "(Front) JAC S5, Hyundai Elantra",
    image: "/images/car-parts/WhatsApp Image 2025-12-09 at 4.41.56 PM.jpeg",
  },
  {
    id: "auto-bp-se-5029",
    name: "Brake Pad Segal SP-BP-SE-5029",
    price: 28,
    category: "Automotive",
    description: "(Rear) MVM X33, 530",
    image: "/images/car-parts/WhatsApp Image 2025-12-09 at 4.41.56 PM (2).jpeg",
  },
  {
    id: "auto-bp-se-5533",
    name: "Brake Pad Segal SP-BP-SE-5533",
    price: 38,
    category: "Automotive",
    description: "(Rear) MVM530, Lifan x60",
    image: "/images/car-parts/WhatsApp Image 2025-12-09 at 4.41.56 PM (1).jpeg",
  },
  {
    id: "auto-bp-se-8942",
    name: "Brake Pad Segal SP-BP-SE-8942",
    price: 34,
    category: "Automotive",
    description: "(Rear) Kia Cerato & Hyundai Avante & Coupe JAC J5",
    image: "/images/car-parts/WhatsApp Image 2025-12-09 at 4.41.55 PM.jpeg",
  },
  {
    id: "auto-bp-se-5005",
    name: "Brake Pad Segal SP-BP-SE-5005",
    price: 43,
    category: "Automotive",
    description: "(Front) Renault Sandero, Symbol, Brilliance Crossover",
    image: "/images/car-parts/WhatsApp Image 2025-12-09 at 4.41.55 PM (1).jpeg",
  },
  {
    id: "auto-bp-se-5028",
    name: "Brake Pad Segal SP-BP-SE-5028",
    price: 39,
    category: "Automotive",
    description: "(Front) MVM X33/315/530",
    image: "/images/car-parts/WhatsApp Image 2025-12-09 at 4.41.54 PM.jpeg",
  },
  {
    id: "auto-bp-se-6800",
    name: "Brake Pad Segal SP-BP-SE-6800",
    price: 38,
    category: "Automotive",
    description: "(Rear) 206, 207",
    image: "/images/car-parts/WhatsApp Image 2025-12-09 at 4.41.54 PM (1).jpeg",
  },
];

export default function Automotive() {
  return (
    <div className="container mx-auto px-4 py-8">
      <div className="mb-8">
        <h1 className="text-4xl font-bold mb-4">Automotive Parts & Accessories</h1>
        <p className="text-muted-foreground text-lg">
          Quality automotive parts and accessories for your vehicle
        </p>
      </div>
      <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-6">
        {automotiveProducts.map((product) => (
          <ProductCard key={product.id} {...product} />
        ))}
      </div>
    </div>
  );
}
