// Fix Prisma 7 client structure - create default.js that @prisma/client expects
const fs = require('fs');
const path = require('path');

const prismaClientPath = path.join(__dirname, '../.prisma/client');
const defaultJsPath = path.join(prismaClientPath, 'default.js');

// Check if .prisma/client directory exists
if (!fs.existsSync(prismaClientPath)) {
  console.log('⚠️  Prisma Client directory not found at', prismaClientPath);
  console.log('   This is normal if Prisma hasn\'t generated yet. Skipping fix.');
  process.exit(0); // Don't fail, just skip
}

// Prisma 7 generates TypeScript files, but @prisma/client/default.js expects a JS file
// We need to create a default.js that properly exports PrismaClient
// The key is to use the Prisma runtime to create the client with the correct path

const defaultContent = `// This file is auto-generated by fix-prisma.js
// Prisma 7 generates TypeScript files, but @prisma/client expects this JS file
// We use the Prisma runtime library to properly load the generated client

const { getPrismaClient } = require('@prisma/client/runtime/library');
const path = require('path');

// Get the path to the generated client
const clientPath = path.join(__dirname);

// Use Prisma's runtime to load the client
const PrismaClient = getPrismaClient({
  // The generated client is in the same directory
  __dirname: clientPath,
});

module.exports = { PrismaClient };
module.exports.PrismaClient = PrismaClient;
`;

fs.writeFileSync(defaultJsPath, defaultContent);
console.log('✅ Created .prisma/client/default.js');

