// Fix Prisma 7 client structure - create default.js that @prisma/client expects
const fs = require('fs');
const path = require('path');

const prismaClientPath = path.join(__dirname, '../node_modules/.prisma/client');
const defaultJsPath = path.join(prismaClientPath, 'default.js');

// Check if .prisma/client directory exists
if (!fs.existsSync(prismaClientPath)) {
  console.log('⚠️  Prisma Client directory not found at', prismaClientPath);
  console.log('   This is normal if Prisma hasn\'t generated yet. Skipping fix.');
  process.exit(0); // Don't fail, just skip
}

// List files to see what Prisma generated
const files = fs.readdirSync(prismaClientPath);
console.log('📁 Files in node_modules/.prisma/client:', files.join(', '));

// Create a default.js that exports from client.ts without circular deps
// The key is to use Object.defineProperty to create lazy getters
const defaultContent = `// This file is auto-generated by fix-prisma.js
// Exports PrismaClient from the generated client.ts

// Create exports object with lazy loading to avoid circular deps
const exports = {};

// Use defineProperty to create lazy getters
Object.defineProperty(exports, 'PrismaClient', {
  get: function() {
    // Try to load from client - Next.js will have compiled the .ts file
    try {
      // In Next.js build, client.ts becomes available
      // We use a try-catch to handle the ES module
      const mod = require('./client');
      return mod.PrismaClient || mod.default?.PrismaClient;
    } catch (e) {
      // If that fails, try the direct path
      try {
        return require('./client.ts').PrismaClient;
      } catch (e2) {
        // Last resort - this shouldn't happen in Next.js
        throw new Error('PrismaClient not found. Run: npx prisma generate');
      }
    }
  },
  enumerable: true,
  configurable: true
});

// Export $Enums and Prisma similarly
Object.defineProperty(exports, '$Enums', {
  get: function() {
    try {
      const mod = require('./client');
      return mod.$Enums || mod.default?.$Enums;
    } catch (e) {
      return require('./enums');
    }
  },
  enumerable: true,
  configurable: true
});

Object.defineProperty(exports, 'Prisma', {
  get: function() {
    try {
      const mod = require('./client');
      return mod.Prisma || mod.default?.Prisma;
    } catch (e) {
      return require('./internal/prismaNamespace');
    }
  },
  enumerable: true,
  configurable: true
});

module.exports = exports;
`;

fs.writeFileSync(defaultJsPath, defaultContent);
console.log('✅ Created node_modules/.prisma/client/default.js');
